[project]
name = "meta-evaluator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pradyuprasad", email = "pradyu.sp@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
meta-evaluator = "meta_evaluator:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pyright>=1.1.401",
    "ruff>=0.11.11",
]

[tool.ruff.lint]
extend-select = ["D", "DOC"]

[tool.ruff.lint.pydocstyle]
convention = "google"

