# .github/workflows/code-quality.yml
name: Code Quality
on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # 1 — Check out the code
      - uses: actions/checkout@v4

      # 2 — Install uv, but turn off its built-in cache
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: false   # we will manage caching explicitly

      # 3 — Restore (or create) a cache keyed to lock-file + pyproject
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv                     # default uv cache dir :contentReference[oaicite:3]{index=3}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock', 'pyproject.toml') }}

      # 4 — Install all declared dependencies every run
      - name: Sync dependencies
        run: uv sync --extra dev

      # 5 — Run the same hooks you use locally
      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

